---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write
        language: node
        additional_dependencies:
          - prettier@3.8.1
        types_or: [yaml, json, markdown]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.5.2
    hooks:
      - id: zizmor
