---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    permissions:
      contents: write
      pull-requests: read
    uses: hassio-addons/workflows/.github/workflows/app-ci.yaml@main
